8867/2024-05-20 10:32:54/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 161, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 45, in setup
    driver.execute_script("window.open('about:blank', '_blank');")
AttributeError: 'NoneType' object has no attribute 'execute_script'

8867/2024-05-20 10:33:36/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 161, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 45, in setup
    driver.execute_script("window.open('about:blank', '_blank');")
AttributeError: 'NoneType' object has no attribute 'execute_script'

8867/2024-05-20 14:19:51/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 127, in save
    save_element = common.find_element("CSS_SELECTOR", ".x1gslohp>.x6s0dn4>.x11i5rnm>div", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 181, in find_element
    return wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector_name)))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x00000001013703e8 chromedriver + 4326376
1   chromedriver                        0x00000001013688b0 chromedriver + 4294832
2   chromedriver                        0x0000000100f94088 chromedriver + 278664
3   chromedriver                        0x0000000100fd6a80 chromedriver + 551552
4   chromedriver                        0x000000010100f4f8 chromedriver + 783608
5   chromedriver                        0x0000000100fcb4e4 chromedriver + 505060
6   chromedriver                        0x0000000100fcbf5c chromedriver + 507740
7   chromedriver                        0x0000000101333984 chromedriver + 4077956
8   chromedriver                        0x000000010133873c chromedriver + 4097852
9   chromedriver                        0x000000010131a528 chromedriver + 3974440
10  chromedriver                        0x0000000101339054 chromedriver + 4100180
11  chromedriver                        0x000000010130bb18 chromedriver + 3914520
12  chromedriver                        0x000000010135965c chromedriver + 4232796
13  chromedriver                        0x00000001013597d8 chromedriver + 4233176
14  chromedriver                        0x0000000101368524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 116, in fetch_order
    result, message = save()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 137, in save
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x00000001013703e8 chromedriver + 4326376
1   chromedriver                        0x00000001013688b0 chromedriver + 4294832
2   chromedriver                        0x0000000100f94088 chromedriver + 278664
3   chromedriver                        0x0000000100fd6a80 chromedriver + 551552
4   chromedriver                        0x000000010100f4f8 chromedriver + 783608
5   chromedriver                        0x0000000100fcb4e4 chromedriver + 505060
6   chromedriver                        0x0000000100fcbf5c chromedriver + 507740
7   chromedriver                        0x0000000101333984 chromedriver + 4077956
8   chromedriver                        0x000000010133873c chromedriver + 4097852
9   chromedriver                        0x000000010131a528 chromedriver + 3974440
10  chromedriver                        0x0000000101339054 chromedriver + 4100180
11  chromedriver                        0x000000010130bb18 chromedriver + 3914520
12  chromedriver                        0x000000010135965c chromedriver + 4232796
13  chromedriver                        0x00000001013597d8 chromedriver + 4233176
14  chromedriver                        0x0000000101368524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 119, in fetch_order
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x00000001013703e8 chromedriver + 4326376
1   chromedriver                        0x00000001013688b0 chromedriver + 4294832
2   chromedriver                        0x0000000100f94088 chromedriver + 278664
3   chromedriver                        0x0000000100fd6a80 chromedriver + 551552
4   chromedriver                        0x000000010100f4f8 chromedriver + 783608
5   chromedriver                        0x0000000100fcb4e4 chromedriver + 505060
6   chromedriver                        0x0000000100fcbf5c chromedriver + 507740
7   chromedriver                        0x0000000101333984 chromedriver + 4077956
8   chromedriver                        0x000000010133873c chromedriver + 4097852
9   chromedriver                        0x000000010131a528 chromedriver + 3974440
10  chromedriver                        0x0000000101339054 chromedriver + 4100180
11  chromedriver                        0x000000010130bb18 chromedriver + 3914520
12  chromedriver                        0x000000010135965c chromedriver + 4232796
13  chromedriver                        0x00000001013597d8 chromedriver + 4233176
14  chromedriver                        0x0000000101368524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


8867/2024-05-20 14:19:51/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 127, in save
    save_element = common.find_element("CSS_SELECTOR", ".x1gslohp>.x6s0dn4>.x11i5rnm>div", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 181, in find_element
    return wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector_name)))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000100b043e8 chromedriver + 4326376
1   chromedriver                        0x0000000100afc8b0 chromedriver + 4294832
2   chromedriver                        0x0000000100728088 chromedriver + 278664
3   chromedriver                        0x000000010076aa80 chromedriver + 551552
4   chromedriver                        0x00000001007a34f8 chromedriver + 783608
5   chromedriver                        0x000000010075f4e4 chromedriver + 505060
6   chromedriver                        0x000000010075ff5c chromedriver + 507740
7   chromedriver                        0x0000000100ac7984 chromedriver + 4077956
8   chromedriver                        0x0000000100acc73c chromedriver + 4097852
9   chromedriver                        0x0000000100aae528 chromedriver + 3974440
10  chromedriver                        0x0000000100acd054 chromedriver + 4100180
11  chromedriver                        0x0000000100a9fb18 chromedriver + 3914520
12  chromedriver                        0x0000000100aed65c chromedriver + 4232796
13  chromedriver                        0x0000000100aed7d8 chromedriver + 4233176
14  chromedriver                        0x0000000100afc524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 116, in fetch_order
    result, message = save()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 137, in save
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x0000000100b043e8 chromedriver + 4326376
1   chromedriver                        0x0000000100afc8b0 chromedriver + 4294832
2   chromedriver                        0x0000000100728088 chromedriver + 278664
3   chromedriver                        0x000000010076aa80 chromedriver + 551552
4   chromedriver                        0x00000001007a34f8 chromedriver + 783608
5   chromedriver                        0x000000010075f4e4 chromedriver + 505060
6   chromedriver                        0x000000010075ff5c chromedriver + 507740
7   chromedriver                        0x0000000100ac7984 chromedriver + 4077956
8   chromedriver                        0x0000000100acc73c chromedriver + 4097852
9   chromedriver                        0x0000000100aae528 chromedriver + 3974440
10  chromedriver                        0x0000000100acd054 chromedriver + 4100180
11  chromedriver                        0x0000000100a9fb18 chromedriver + 3914520
12  chromedriver                        0x0000000100aed65c chromedriver + 4232796
13  chromedriver                        0x0000000100aed7d8 chromedriver + 4233176
14  chromedriver                        0x0000000100afc524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 119, in fetch_order
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x0000000100b043e8 chromedriver + 4326376
1   chromedriver                        0x0000000100afc8b0 chromedriver + 4294832
2   chromedriver                        0x0000000100728088 chromedriver + 278664
3   chromedriver                        0x000000010076aa80 chromedriver + 551552
4   chromedriver                        0x00000001007a34f8 chromedriver + 783608
5   chromedriver                        0x000000010075f4e4 chromedriver + 505060
6   chromedriver                        0x000000010075ff5c chromedriver + 507740
7   chromedriver                        0x0000000100ac7984 chromedriver + 4077956
8   chromedriver                        0x0000000100acc73c chromedriver + 4097852
9   chromedriver                        0x0000000100aae528 chromedriver + 3974440
10  chromedriver                        0x0000000100acd054 chromedriver + 4100180
11  chromedriver                        0x0000000100a9fb18 chromedriver + 3914520
12  chromedriver                        0x0000000100aed65c chromedriver + 4232796
13  chromedriver                        0x0000000100aed7d8 chromedriver + 4233176
14  chromedriver                        0x0000000100afc524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


8867/2024-05-20 14:22:13/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 127, in save
    save_element = common.find_element("CSS_SELECTOR", ".x1gslohp>.x6s0dn4>.x11i5rnm>div", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 181, in find_element
    return wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector_name)))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000100d5c3e8 chromedriver + 4326376
1   chromedriver                        0x0000000100d548b0 chromedriver + 4294832
2   chromedriver                        0x0000000100980088 chromedriver + 278664
3   chromedriver                        0x00000001009c2a80 chromedriver + 551552
4   chromedriver                        0x00000001009fb4f8 chromedriver + 783608
5   chromedriver                        0x00000001009b74e4 chromedriver + 505060
6   chromedriver                        0x00000001009b7f5c chromedriver + 507740
7   chromedriver                        0x0000000100d1f984 chromedriver + 4077956
8   chromedriver                        0x0000000100d2473c chromedriver + 4097852
9   chromedriver                        0x0000000100d06528 chromedriver + 3974440
10  chromedriver                        0x0000000100d25054 chromedriver + 4100180
11  chromedriver                        0x0000000100cf7b18 chromedriver + 3914520
12  chromedriver                        0x0000000100d4565c chromedriver + 4232796
13  chromedriver                        0x0000000100d457d8 chromedriver + 4233176
14  chromedriver                        0x0000000100d54524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 116, in fetch_order
    result, message = save()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 137, in save
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x0000000100d5c3e8 chromedriver + 4326376
1   chromedriver                        0x0000000100d548b0 chromedriver + 4294832
2   chromedriver                        0x0000000100980088 chromedriver + 278664
3   chromedriver                        0x00000001009c2a80 chromedriver + 551552
4   chromedriver                        0x00000001009fb4f8 chromedriver + 783608
5   chromedriver                        0x00000001009b74e4 chromedriver + 505060
6   chromedriver                        0x00000001009b7f5c chromedriver + 507740
7   chromedriver                        0x0000000100d1f984 chromedriver + 4077956
8   chromedriver                        0x0000000100d2473c chromedriver + 4097852
9   chromedriver                        0x0000000100d06528 chromedriver + 3974440
10  chromedriver                        0x0000000100d25054 chromedriver + 4100180
11  chromedriver                        0x0000000100cf7b18 chromedriver + 3914520
12  chromedriver                        0x0000000100d4565c chromedriver + 4232796
13  chromedriver                        0x0000000100d457d8 chromedriver + 4233176
14  chromedriver                        0x0000000100d54524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 119, in fetch_order
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x0000000100d5c3e8 chromedriver + 4326376
1   chromedriver                        0x0000000100d548b0 chromedriver + 4294832
2   chromedriver                        0x0000000100980088 chromedriver + 278664
3   chromedriver                        0x00000001009c2a80 chromedriver + 551552
4   chromedriver                        0x00000001009fb4f8 chromedriver + 783608
5   chromedriver                        0x00000001009b74e4 chromedriver + 505060
6   chromedriver                        0x00000001009b7f5c chromedriver + 507740
7   chromedriver                        0x0000000100d1f984 chromedriver + 4077956
8   chromedriver                        0x0000000100d2473c chromedriver + 4097852
9   chromedriver                        0x0000000100d06528 chromedriver + 3974440
10  chromedriver                        0x0000000100d25054 chromedriver + 4100180
11  chromedriver                        0x0000000100cf7b18 chromedriver + 3914520
12  chromedriver                        0x0000000100d4565c chromedriver + 4232796
13  chromedriver                        0x0000000100d457d8 chromedriver + 4233176
14  chromedriver                        0x0000000100d54524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


8867/2024-05-20 14:22:13/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 127, in save
    save_element = common.find_element("CSS_SELECTOR", ".x1gslohp>.x6s0dn4>.x11i5rnm>div", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 181, in find_element
    return wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector_name)))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x00000001046783e8 chromedriver + 4326376
1   chromedriver                        0x00000001046708b0 chromedriver + 4294832
2   chromedriver                        0x000000010429c088 chromedriver + 278664
3   chromedriver                        0x00000001042dea80 chromedriver + 551552
4   chromedriver                        0x00000001043174f8 chromedriver + 783608
5   chromedriver                        0x00000001042d34e4 chromedriver + 505060
6   chromedriver                        0x00000001042d3f5c chromedriver + 507740
7   chromedriver                        0x000000010463b984 chromedriver + 4077956
8   chromedriver                        0x000000010464073c chromedriver + 4097852
9   chromedriver                        0x0000000104622528 chromedriver + 3974440
10  chromedriver                        0x0000000104641054 chromedriver + 4100180
11  chromedriver                        0x0000000104613b18 chromedriver + 3914520
12  chromedriver                        0x000000010466165c chromedriver + 4232796
13  chromedriver                        0x00000001046617d8 chromedriver + 4233176
14  chromedriver                        0x0000000104670524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 116, in fetch_order
    result, message = save()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 137, in save
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x00000001046783e8 chromedriver + 4326376
1   chromedriver                        0x00000001046708b0 chromedriver + 4294832
2   chromedriver                        0x000000010429c088 chromedriver + 278664
3   chromedriver                        0x00000001042dea80 chromedriver + 551552
4   chromedriver                        0x00000001043174f8 chromedriver + 783608
5   chromedriver                        0x00000001042d34e4 chromedriver + 505060
6   chromedriver                        0x00000001042d3f5c chromedriver + 507740
7   chromedriver                        0x000000010463b984 chromedriver + 4077956
8   chromedriver                        0x000000010464073c chromedriver + 4097852
9   chromedriver                        0x0000000104622528 chromedriver + 3974440
10  chromedriver                        0x0000000104641054 chromedriver + 4100180
11  chromedriver                        0x0000000104613b18 chromedriver + 3914520
12  chromedriver                        0x000000010466165c chromedriver + 4232796
13  chromedriver                        0x00000001046617d8 chromedriver + 4233176
14  chromedriver                        0x0000000104670524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 119, in fetch_order
    raise Exception(ex)
Exception: Message: 
Stacktrace:
0   chromedriver                        0x00000001046783e8 chromedriver + 4326376
1   chromedriver                        0x00000001046708b0 chromedriver + 4294832
2   chromedriver                        0x000000010429c088 chromedriver + 278664
3   chromedriver                        0x00000001042dea80 chromedriver + 551552
4   chromedriver                        0x00000001043174f8 chromedriver + 783608
5   chromedriver                        0x00000001042d34e4 chromedriver + 505060
6   chromedriver                        0x00000001042d3f5c chromedriver + 507740
7   chromedriver                        0x000000010463b984 chromedriver + 4077956
8   chromedriver                        0x000000010464073c chromedriver + 4097852
9   chromedriver                        0x0000000104622528 chromedriver + 3974440
10  chromedriver                        0x0000000104641054 chromedriver + 4100180
11  chromedriver                        0x0000000104613b18 chromedriver + 3914520
12  chromedriver                        0x000000010466165c chromedriver + 4232796
13  chromedriver                        0x00000001046617d8 chromedriver + 4233176
14  chromedriver                        0x0000000104670524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


8867/2024-05-20 15:05:24/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 132, in save
    common.click(save_element)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 535, in click
    element.click()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.208)
Stacktrace:
0   chromedriver                        0x00000001006bc3e8 chromedriver + 4326376
1   chromedriver                        0x00000001006b48b0 chromedriver + 4294832
2   chromedriver                        0x00000001002e0088 chromedriver + 278664
3   chromedriver                        0x00000001002bb270 chromedriver + 127600
4   chromedriver                        0x00000001003479ac chromedriver + 702892
5   chromedriver                        0x000000010035ac0c chromedriver + 781324
6   chromedriver                        0x00000001003174e4 chromedriver + 505060
7   chromedriver                        0x0000000100317f5c chromedriver + 507740
8   chromedriver                        0x000000010067f984 chromedriver + 4077956
9   chromedriver                        0x000000010068473c chromedriver + 4097852
10  chromedriver                        0x0000000100666528 chromedriver + 3974440
11  chromedriver                        0x0000000100685054 chromedriver + 4100180
12  chromedriver                        0x0000000100657b18 chromedriver + 3914520
13  chromedriver                        0x00000001006a565c chromedriver + 4232796
14  chromedriver                        0x00000001006a57d8 chromedriver + 4233176
15  chromedriver                        0x00000001006b4524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 116, in fetch_order
    result, message = save()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 137, in save
    raise Exception(ex)
Exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.208)
Stacktrace:
0   chromedriver                        0x00000001006bc3e8 chromedriver + 4326376
1   chromedriver                        0x00000001006b48b0 chromedriver + 4294832
2   chromedriver                        0x00000001002e0088 chromedriver + 278664
3   chromedriver                        0x00000001002bb270 chromedriver + 127600
4   chromedriver                        0x00000001003479ac chromedriver + 702892
5   chromedriver                        0x000000010035ac0c chromedriver + 781324
6   chromedriver                        0x00000001003174e4 chromedriver + 505060
7   chromedriver                        0x0000000100317f5c chromedriver + 507740
8   chromedriver                        0x000000010067f984 chromedriver + 4077956
9   chromedriver                        0x000000010068473c chromedriver + 4097852
10  chromedriver                        0x0000000100666528 chromedriver + 3974440
11  chromedriver                        0x0000000100685054 chromedriver + 4100180
12  chromedriver                        0x0000000100657b18 chromedriver + 3914520
13  chromedriver                        0x00000001006a565c chromedriver + 4232796
14  chromedriver                        0x00000001006a57d8 chromedriver + 4233176
15  chromedriver                        0x00000001006b4524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 119, in fetch_order
    raise Exception(ex)
Exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.208)
Stacktrace:
0   chromedriver                        0x00000001006bc3e8 chromedriver + 4326376
1   chromedriver                        0x00000001006b48b0 chromedriver + 4294832
2   chromedriver                        0x00000001002e0088 chromedriver + 278664
3   chromedriver                        0x00000001002bb270 chromedriver + 127600
4   chromedriver                        0x00000001003479ac chromedriver + 702892
5   chromedriver                        0x000000010035ac0c chromedriver + 781324
6   chromedriver                        0x00000001003174e4 chromedriver + 505060
7   chromedriver                        0x0000000100317f5c chromedriver + 507740
8   chromedriver                        0x000000010067f984 chromedriver + 4077956
9   chromedriver                        0x000000010068473c chromedriver + 4097852
10  chromedriver                        0x0000000100666528 chromedriver + 3974440
11  chromedriver                        0x0000000100685054 chromedriver + 4100180
12  chromedriver                        0x0000000100657b18 chromedriver + 3914520
13  chromedriver                        0x00000001006a565c chromedriver + 4232796
14  chromedriver                        0x00000001006a57d8 chromedriver + 4233176
15  chromedriver                        0x00000001006b4524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x000000018a9b2f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000018a9add34 thread_start + 8


8867/2024-05-20 15:46:45/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 162, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 46, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 67, in dashboard
    print(svg.get_attubete("aria-label"))
AttributeError: 'WebElement' object has no attribute 'get_attubete'. Did you mean: 'get_attribute'?

8867/2024-05-21 13:29:48/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/follow/../follow/follow_main.py", line 164, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/follow/../follow/follow_main.py", line 46, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/follow/../follow/follow_main.py", line 70, in dashboard
    if not is_login:
UnboundLocalError: local variable 'is_login' referenced before assignment

8867/2024-05-21 13:35:28/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/follow/../follow/follow_main.py", line 165, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/follow/../follow/follow_main.py", line 46, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/follow/../follow/follow_main.py", line 65, in dashboard
    svgs = common.find_elements("TAG_NAME", "svg", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/follow/../common/fun.py", line 206, in find_elements
    return wait.until(EC.presence_of_all_elements_located((By.TAG_NAME, selector_name)))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


