1/2024-04-18 20:21:36/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 149, in login
    id_input = common.find_element('NAME', "username", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 114, in find_element
    if not is_display(selector_type, selector_name, driver):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 194, in is_display
    count = len(driver.find_elements(By.NAME, selector_name))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 771, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001046e43e8 chromedriver + 4326376
1   chromedriver                        0x00000001046dc8b0 chromedriver + 4294832
2   chromedriver                        0x0000000104308088 chromedriver + 278664
3   chromedriver                        0x00000001042e3270 chromedriver + 127600
4   chromedriver                        0x000000010436f9ac chromedriver + 702892
5   chromedriver                        0x0000000104382c0c chromedriver + 781324
6   chromedriver                        0x000000010433f4e4 chromedriver + 505060
7   chromedriver                        0x000000010433ff5c chromedriver + 507740
8   chromedriver                        0x00000001046a7984 chromedriver + 4077956
9   chromedriver                        0x00000001046ac73c chromedriver + 4097852
10  chromedriver                        0x000000010468e528 chromedriver + 3974440
11  chromedriver                        0x00000001046ad054 chromedriver + 4100180
12  chromedriver                        0x000000010467fb18 chromedriver + 3914520
13  chromedriver                        0x00000001046cd65c chromedriver + 4232796
14  chromedriver                        0x00000001046cd7d8 chromedriver + 4233176
15  chromedriver                        0x00000001046dc524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 180, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 67, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 87, in dashboard
    login(user_id, user_pw)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 165, in login
    raise Exception('로그인 에러')
Exception: 로그인 에러

1/2024-04-18 20:27:12/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 186, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 68, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 78, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000104b903e8 chromedriver + 4326376
1   chromedriver                        0x0000000104b888b0 chromedriver + 4294832
2   chromedriver                        0x00000001047b4088 chromedriver + 278664
3   chromedriver                        0x00000001047ace94 chromedriver + 249492
4   chromedriver                        0x000000010479e658 chromedriver + 190040
5   chromedriver                        0x000000010479f91c chromedriver + 194844
6   chromedriver                        0x000000010479e930 chromedriver + 190768
7   chromedriver                        0x000000010479e378 chromedriver + 189304
8   chromedriver                        0x000000010479e018 chromedriver + 188440
9   chromedriver                        0x000000010479be60 chromedriver + 179808
10  chromedriver                        0x000000010479c7fc chromedriver + 182268
11  chromedriver                        0x00000001047b6620 chromedriver + 288288
12  chromedriver                        0x000000010482fb14 chromedriver + 785172
13  chromedriver                        0x000000010482f4f8 chromedriver + 783608
14  chromedriver                        0x00000001047eb4e4 chromedriver + 505060
15  chromedriver                        0x00000001047ebf5c chromedriver + 507740
16  chromedriver                        0x0000000104b53984 chromedriver + 4077956
17  chromedriver                        0x0000000104b5873c chromedriver + 4097852
18  chromedriver                        0x0000000104b3a528 chromedriver + 3974440
19  chromedriver                        0x0000000104b59054 chromedriver + 4100180
20  chromedriver                        0x0000000104b2bb18 chromedriver + 3914520
21  chromedriver                        0x0000000104b7965c chromedriver + 4232796
22  chromedriver                        0x0000000104b797d8 chromedriver + 4233176
23  chromedriver                        0x0000000104b88524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


1/2024-04-18 20:28:07/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 188, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 80, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001051c03e8 chromedriver + 4326376
1   chromedriver                        0x00000001051b88b0 chromedriver + 4294832
2   chromedriver                        0x0000000104de4088 chromedriver + 278664
3   chromedriver                        0x0000000104ddce94 chromedriver + 249492
4   chromedriver                        0x0000000104dce658 chromedriver + 190040
5   chromedriver                        0x0000000104dcf91c chromedriver + 194844
6   chromedriver                        0x0000000104dce930 chromedriver + 190768
7   chromedriver                        0x0000000104dce378 chromedriver + 189304
8   chromedriver                        0x0000000104dce018 chromedriver + 188440
9   chromedriver                        0x0000000104dcbe60 chromedriver + 179808
10  chromedriver                        0x0000000104dcc7fc chromedriver + 182268
11  chromedriver                        0x0000000104de6620 chromedriver + 288288
12  chromedriver                        0x0000000104e5fb14 chromedriver + 785172
13  chromedriver                        0x0000000104e5f4f8 chromedriver + 783608
14  chromedriver                        0x0000000104e1b4e4 chromedriver + 505060
15  chromedriver                        0x0000000104e1bf5c chromedriver + 507740
16  chromedriver                        0x0000000105183984 chromedriver + 4077956
17  chromedriver                        0x000000010518873c chromedriver + 4097852
18  chromedriver                        0x000000010516a528 chromedriver + 3974440
19  chromedriver                        0x0000000105189054 chromedriver + 4100180
20  chromedriver                        0x000000010515bb18 chromedriver + 3914520
21  chromedriver                        0x00000001051a965c chromedriver + 4232796
22  chromedriver                        0x00000001051a97d8 chromedriver + 4233176
23  chromedriver                        0x00000001051b8524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


1/2024-04-18 20:28:33/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 188, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 80, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001027b43e8 chromedriver + 4326376
1   chromedriver                        0x00000001027ac8b0 chromedriver + 4294832
2   chromedriver                        0x00000001023d8088 chromedriver + 278664
3   chromedriver                        0x00000001023d0e94 chromedriver + 249492
4   chromedriver                        0x00000001023c2658 chromedriver + 190040
5   chromedriver                        0x00000001023c391c chromedriver + 194844
6   chromedriver                        0x00000001023c2930 chromedriver + 190768
7   chromedriver                        0x00000001023c2378 chromedriver + 189304
8   chromedriver                        0x00000001023c2018 chromedriver + 188440
9   chromedriver                        0x00000001023bfe60 chromedriver + 179808
10  chromedriver                        0x00000001023c07fc chromedriver + 182268
11  chromedriver                        0x00000001023da620 chromedriver + 288288
12  chromedriver                        0x0000000102453b14 chromedriver + 785172
13  chromedriver                        0x00000001024534f8 chromedriver + 783608
14  chromedriver                        0x000000010240f4e4 chromedriver + 505060
15  chromedriver                        0x000000010240ff5c chromedriver + 507740
16  chromedriver                        0x0000000102777984 chromedriver + 4077956
17  chromedriver                        0x000000010277c73c chromedriver + 4097852
18  chromedriver                        0x000000010275e528 chromedriver + 3974440
19  chromedriver                        0x000000010277d054 chromedriver + 4100180
20  chromedriver                        0x000000010274fb18 chromedriver + 3914520
21  chromedriver                        0x000000010279d65c chromedriver + 4232796
22  chromedriver                        0x000000010279d7d8 chromedriver + 4233176
23  chromedriver                        0x00000001027ac524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


1/2024-04-18 20:30:34/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 187, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 69, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 79, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001024943e8 chromedriver + 4326376
1   chromedriver                        0x000000010248c8b0 chromedriver + 4294832
2   chromedriver                        0x00000001020b8088 chromedriver + 278664
3   chromedriver                        0x00000001020b0e94 chromedriver + 249492
4   chromedriver                        0x00000001020a2658 chromedriver + 190040
5   chromedriver                        0x00000001020a391c chromedriver + 194844
6   chromedriver                        0x00000001020a2930 chromedriver + 190768
7   chromedriver                        0x00000001020a2378 chromedriver + 189304
8   chromedriver                        0x00000001020a2018 chromedriver + 188440
9   chromedriver                        0x000000010209fe60 chromedriver + 179808
10  chromedriver                        0x00000001020a07fc chromedriver + 182268
11  chromedriver                        0x00000001020ba620 chromedriver + 288288
12  chromedriver                        0x0000000102133b14 chromedriver + 785172
13  chromedriver                        0x00000001021334f8 chromedriver + 783608
14  chromedriver                        0x00000001020ef4e4 chromedriver + 505060
15  chromedriver                        0x00000001020eff5c chromedriver + 507740
16  chromedriver                        0x0000000102457984 chromedriver + 4077956
17  chromedriver                        0x000000010245c73c chromedriver + 4097852
18  chromedriver                        0x000000010243e528 chromedriver + 3974440
19  chromedriver                        0x000000010245d054 chromedriver + 4100180
20  chromedriver                        0x000000010242fb18 chromedriver + 3914520
21  chromedriver                        0x000000010247d65c chromedriver + 4232796
22  chromedriver                        0x000000010247d7d8 chromedriver + 4233176
23  chromedriver                        0x000000010248c524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


1/2024-04-18 20:31:33/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 156, in login
    id_input = common.find_element('NAME', "username", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 114, in find_element
    if not is_display(selector_type, selector_name, driver):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 194, in is_display
    count = len(driver.find_elements(By.NAME, selector_name))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 771, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001026003e8 chromedriver + 4326376
1   chromedriver                        0x00000001025f88b0 chromedriver + 4294832
2   chromedriver                        0x0000000102224088 chromedriver + 278664
3   chromedriver                        0x00000001021ff270 chromedriver + 127600
4   chromedriver                        0x000000010228b9ac chromedriver + 702892
5   chromedriver                        0x000000010229ec0c chromedriver + 781324
6   chromedriver                        0x000000010225b4e4 chromedriver + 505060
7   chromedriver                        0x000000010225bf5c chromedriver + 507740
8   chromedriver                        0x00000001025c3984 chromedriver + 4077956
9   chromedriver                        0x00000001025c873c chromedriver + 4097852
10  chromedriver                        0x00000001025aa528 chromedriver + 3974440
11  chromedriver                        0x00000001025c9054 chromedriver + 4100180
12  chromedriver                        0x000000010259bb18 chromedriver + 3914520
13  chromedriver                        0x00000001025e965c chromedriver + 4232796
14  chromedriver                        0x00000001025e97d8 chromedriver + 4233176
15  chromedriver                        0x00000001025f8524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 187, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 69, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 94, in dashboard
    login(user_id, user_pw)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 172, in login
    raise Exception('로그인 에러')
Exception: 로그인 에러

8867/2024-04-18 20:44:09/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 168, in login
    login_btn.click()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class=" _acan _acap _acas _aj1- _ap30" disabled="" type="submit">...</button> is not clickable at point (242, 301). Other element would receive the click: <div class="x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh x1xmf6yo x1e56ztr x540dpk x1m39q7l x1n2onr6 x1plvlek xryxfnj x1c4vz4f x2lah0s xdt5ytf xqjyukv x1qjc9v5 x1oa3qoh x1nhvcw1">...</div>
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001047743e8 chromedriver + 4326376
1   chromedriver                        0x000000010476c8b0 chromedriver + 4294832
2   chromedriver                        0x0000000104398088 chromedriver + 278664
3   chromedriver                        0x00000001043e0554 chromedriver + 574804
4   chromedriver                        0x00000001043dead8 chromedriver + 568024
5   chromedriver                        0x00000001043dcc58 chromedriver + 560216
6   chromedriver                        0x00000001043dc188 chromedriver + 557448
7   chromedriver                        0x00000001043d13ac chromedriver + 512940
8   chromedriver                        0x00000001043d0dd0 chromedriver + 511440
9   chromedriver                        0x00000001044134f8 chromedriver + 783608
10  chromedriver                        0x00000001043cf4e4 chromedriver + 505060
11  chromedriver                        0x00000001043cff5c chromedriver + 507740
12  chromedriver                        0x0000000104737984 chromedriver + 4077956
13  chromedriver                        0x000000010473c73c chromedriver + 4097852
14  chromedriver                        0x000000010471e528 chromedriver + 3974440
15  chromedriver                        0x000000010473d054 chromedriver + 4100180
16  chromedriver                        0x000000010470fb18 chromedriver + 3914520
17  chromedriver                        0x000000010475d65c chromedriver + 4232796
18  chromedriver                        0x000000010475d7d8 chromedriver + 4233176
19  chromedriver                        0x000000010476c524 chromedriver + 4293924
20  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
21  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 187, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 69, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 94, in dashboard
    login(user_id, user_pw)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 172, in login
    raise Exception('로그인 에러')
Exception: 로그인 에러

8867/2024-04-18 20:44:09/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 168, in login
    login_btn.click()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class=" _acan _acap _acas _aj1- _ap30" disabled="" type="submit">...</button> is not clickable at point (242, 301). Other element would receive the click: <div class="x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh x1xmf6yo x1e56ztr x540dpk x1m39q7l x1n2onr6 x1plvlek xryxfnj x1c4vz4f x2lah0s xdt5ytf xqjyukv x1qjc9v5 x1oa3qoh x1nhvcw1">...</div>
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001033383e8 chromedriver + 4326376
1   chromedriver                        0x00000001033308b0 chromedriver + 4294832
2   chromedriver                        0x0000000102f5c088 chromedriver + 278664
3   chromedriver                        0x0000000102fa4554 chromedriver + 574804
4   chromedriver                        0x0000000102fa2ad8 chromedriver + 568024
5   chromedriver                        0x0000000102fa0c58 chromedriver + 560216
6   chromedriver                        0x0000000102fa0188 chromedriver + 557448
7   chromedriver                        0x0000000102f953ac chromedriver + 512940
8   chromedriver                        0x0000000102f94dd0 chromedriver + 511440
9   chromedriver                        0x0000000102fd74f8 chromedriver + 783608
10  chromedriver                        0x0000000102f934e4 chromedriver + 505060
11  chromedriver                        0x0000000102f93f5c chromedriver + 507740
12  chromedriver                        0x00000001032fb984 chromedriver + 4077956
13  chromedriver                        0x000000010330073c chromedriver + 4097852
14  chromedriver                        0x00000001032e2528 chromedriver + 3974440
15  chromedriver                        0x0000000103301054 chromedriver + 4100180
16  chromedriver                        0x00000001032d3b18 chromedriver + 3914520
17  chromedriver                        0x000000010332165c chromedriver + 4232796
18  chromedriver                        0x00000001033217d8 chromedriver + 4233176
19  chromedriver                        0x0000000103330524 chromedriver + 4293924
20  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
21  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 187, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 69, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 94, in dashboard
    login(user_id, user_pw)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 172, in login
    raise Exception('로그인 에러')
Exception: 로그인 에러

8867/2024-04-18 21:10:26/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 126, in fetch_order
    driver.get(order_url)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x000000010099c3e8 chromedriver + 4326376
1   chromedriver                        0x00000001009948b0 chromedriver + 4294832
2   chromedriver                        0x00000001005c0088 chromedriver + 278664
3   chromedriver                        0x000000010059b270 chromedriver + 127600
4   chromedriver                        0x00000001006279ac chromedriver + 702892
5   chromedriver                        0x000000010063ac0c chromedriver + 781324
6   chromedriver                        0x00000001005f74e4 chromedriver + 505060
7   chromedriver                        0x00000001005f7f5c chromedriver + 507740
8   chromedriver                        0x000000010095f984 chromedriver + 4077956
9   chromedriver                        0x000000010096473c chromedriver + 4097852
10  chromedriver                        0x0000000100946528 chromedriver + 3974440
11  chromedriver                        0x0000000100965054 chromedriver + 4100180
12  chromedriver                        0x0000000100937b18 chromedriver + 3914520
13  chromedriver                        0x000000010098565c chromedriver + 4232796
14  chromedriver                        0x00000001009857d8 chromedriver + 4233176
15  chromedriver                        0x0000000100994524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 106, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 130, in fetch_order
    raise Exception(ex)
Exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x000000010099c3e8 chromedriver + 4326376
1   chromedriver                        0x00000001009948b0 chromedriver + 4294832
2   chromedriver                        0x00000001005c0088 chromedriver + 278664
3   chromedriver                        0x000000010059b270 chromedriver + 127600
4   chromedriver                        0x00000001006279ac chromedriver + 702892
5   chromedriver                        0x000000010063ac0c chromedriver + 781324
6   chromedriver                        0x00000001005f74e4 chromedriver + 505060
7   chromedriver                        0x00000001005f7f5c chromedriver + 507740
8   chromedriver                        0x000000010095f984 chromedriver + 4077956
9   chromedriver                        0x000000010096473c chromedriver + 4097852
10  chromedriver                        0x0000000100946528 chromedriver + 3974440
11  chromedriver                        0x0000000100965054 chromedriver + 4100180
12  chromedriver                        0x0000000100937b18 chromedriver + 3914520
13  chromedriver                        0x000000010098565c chromedriver + 4232796
14  chromedriver                        0x00000001009857d8 chromedriver + 4233176
15  chromedriver                        0x0000000100994524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x000000018a602f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x000000018a5fdd34 thread_start + 8


8867/2024-04-19 09:46:03/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 137, in save
    save_element = common.find_element("CSS_SELECTOR", ".x1gslohp>.x6s0dn4>.x11i5rnm>div", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 124, in find_element
    if not is_display(selector_type, selector_name, driver):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 208, in is_display
    count = len(driver.find_elements(By.CSS_SELECTOR, selector_name))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 771, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001046983e8 chromedriver + 4326376
1   chromedriver                        0x00000001046908b0 chromedriver + 4294832
2   chromedriver                        0x00000001042bc088 chromedriver + 278664
3   chromedriver                        0x0000000104297270 chromedriver + 127600
4   chromedriver                        0x00000001043239ac chromedriver + 702892
5   chromedriver                        0x0000000104336c0c chromedriver + 781324
6   chromedriver                        0x00000001042f34e4 chromedriver + 505060
7   chromedriver                        0x00000001042f3f5c chromedriver + 507740
8   chromedriver                        0x000000010465b984 chromedriver + 4077956
9   chromedriver                        0x000000010466073c chromedriver + 4097852
10  chromedriver                        0x0000000104642528 chromedriver + 3974440
11  chromedriver                        0x0000000104661054 chromedriver + 4100180
12  chromedriver                        0x0000000104633b18 chromedriver + 3914520
13  chromedriver                        0x000000010468165c chromedriver + 4232796
14  chromedriver                        0x00000001046817d8 chromedriver + 4233176
15  chromedriver                        0x0000000104690524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 127, in fetch_order
    result, message = save()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 146, in save
    raise Exception(ex)
Exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001046983e8 chromedriver + 4326376
1   chromedriver                        0x00000001046908b0 chromedriver + 4294832
2   chromedriver                        0x00000001042bc088 chromedriver + 278664
3   chromedriver                        0x0000000104297270 chromedriver + 127600
4   chromedriver                        0x00000001043239ac chromedriver + 702892
5   chromedriver                        0x0000000104336c0c chromedriver + 781324
6   chromedriver                        0x00000001042f34e4 chromedriver + 505060
7   chromedriver                        0x00000001042f3f5c chromedriver + 507740
8   chromedriver                        0x000000010465b984 chromedriver + 4077956
9   chromedriver                        0x000000010466073c chromedriver + 4097852
10  chromedriver                        0x0000000104642528 chromedriver + 3974440
11  chromedriver                        0x0000000104661054 chromedriver + 4100180
12  chromedriver                        0x0000000104633b18 chromedriver + 3914520
13  chromedriver                        0x000000010468165c chromedriver + 4232796
14  chromedriver                        0x00000001046817d8 chromedriver + 4233176
15  chromedriver                        0x0000000104690524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 106, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 130, in fetch_order
    raise Exception(ex)
Exception: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001046983e8 chromedriver + 4326376
1   chromedriver                        0x00000001046908b0 chromedriver + 4294832
2   chromedriver                        0x00000001042bc088 chromedriver + 278664
3   chromedriver                        0x0000000104297270 chromedriver + 127600
4   chromedriver                        0x00000001043239ac chromedriver + 702892
5   chromedriver                        0x0000000104336c0c chromedriver + 781324
6   chromedriver                        0x00000001042f34e4 chromedriver + 505060
7   chromedriver                        0x00000001042f3f5c chromedriver + 507740
8   chromedriver                        0x000000010465b984 chromedriver + 4077956
9   chromedriver                        0x000000010466073c chromedriver + 4097852
10  chromedriver                        0x0000000104642528 chromedriver + 3974440
11  chromedriver                        0x0000000104661054 chromedriver + 4100180
12  chromedriver                        0x0000000104633b18 chromedriver + 3914520
13  chromedriver                        0x000000010468165c chromedriver + 4232796
14  chromedriver                        0x00000001046817d8 chromedriver + 4233176
15  chromedriver                        0x0000000104690524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 09:46:27/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 196, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 69, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 79, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102a683e8 chromedriver + 4326376
1   chromedriver                        0x0000000102a608b0 chromedriver + 4294832
2   chromedriver                        0x000000010268c088 chromedriver + 278664
3   chromedriver                        0x0000000102684e94 chromedriver + 249492
4   chromedriver                        0x0000000102676658 chromedriver + 190040
5   chromedriver                        0x000000010267791c chromedriver + 194844
6   chromedriver                        0x0000000102676930 chromedriver + 190768
7   chromedriver                        0x0000000102676378 chromedriver + 189304
8   chromedriver                        0x0000000102676018 chromedriver + 188440
9   chromedriver                        0x0000000102673e60 chromedriver + 179808
10  chromedriver                        0x00000001026747fc chromedriver + 182268
11  chromedriver                        0x000000010268e620 chromedriver + 288288
12  chromedriver                        0x0000000102707b14 chromedriver + 785172
13  chromedriver                        0x00000001027074f8 chromedriver + 783608
14  chromedriver                        0x00000001026c34e4 chromedriver + 505060
15  chromedriver                        0x00000001026c3f5c chromedriver + 507740
16  chromedriver                        0x0000000102a2b984 chromedriver + 4077956
17  chromedriver                        0x0000000102a3073c chromedriver + 4097852
18  chromedriver                        0x0000000102a12528 chromedriver + 3974440
19  chromedriver                        0x0000000102a31054 chromedriver + 4100180
20  chromedriver                        0x0000000102a03b18 chromedriver + 3914520
21  chromedriver                        0x0000000102a5165c chromedriver + 4232796
22  chromedriver                        0x0000000102a517d8 chromedriver + 4233176
23  chromedriver                        0x0000000102a60524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 09:48:25/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 203, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    selenium_driver = webdriver.Chrome(service=service, options=options, proxy_options=proxy_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'proxy_options'

8867/2024-04-19 09:48:39/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 203, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    selenium_driver = webdriver.Chrome(service=service, options=options, proxy=proxy_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'proxy'

8867/2024-04-19 09:49:43/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 202, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 69, in setup
    selenium_driver = webdriver.Chrome(service=service, options=options, seleniumwire_options=proxy_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'seleniumwire_options'

8867/2024-04-19 09:50:06/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 202, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 69, in setup
    selenium_driver = webdriver.Chrome(service=service, options=options, seleniumwire_options=proxy_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'seleniumwire_options'

8867/2024-04-19 09:51:34/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 203, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    selenium_driver = webdriver.Chrome(service=service, options=options, proxy=proxy)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'proxy'

8867/2024-04-19 09:52:39/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 203, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 76, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 86, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000100ea83e8 chromedriver + 4326376
1   chromedriver                        0x0000000100ea08b0 chromedriver + 4294832
2   chromedriver                        0x0000000100acc088 chromedriver + 278664
3   chromedriver                        0x0000000100ac4e94 chromedriver + 249492
4   chromedriver                        0x0000000100ab6658 chromedriver + 190040
5   chromedriver                        0x0000000100ab791c chromedriver + 194844
6   chromedriver                        0x0000000100ab6930 chromedriver + 190768
7   chromedriver                        0x0000000100ab6378 chromedriver + 189304
8   chromedriver                        0x0000000100ab6018 chromedriver + 188440
9   chromedriver                        0x0000000100ab3e60 chromedriver + 179808
10  chromedriver                        0x0000000100ab47fc chromedriver + 182268
11  chromedriver                        0x0000000100ace620 chromedriver + 288288
12  chromedriver                        0x0000000100b47b14 chromedriver + 785172
13  chromedriver                        0x0000000100b474f8 chromedriver + 783608
14  chromedriver                        0x0000000100b034e4 chromedriver + 505060
15  chromedriver                        0x0000000100b03f5c chromedriver + 507740
16  chromedriver                        0x0000000100e6b984 chromedriver + 4077956
17  chromedriver                        0x0000000100e7073c chromedriver + 4097852
18  chromedriver                        0x0000000100e52528 chromedriver + 3974440
19  chromedriver                        0x0000000100e71054 chromedriver + 4100180
20  chromedriver                        0x0000000100e43b18 chromedriver + 3914520
21  chromedriver                        0x0000000100e9165c chromedriver + 4232796
22  chromedriver                        0x0000000100e917d8 chromedriver + 4233176
23  chromedriver                        0x0000000100ea0524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 09:53:30/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 206, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 79, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 89, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001047c43e8 chromedriver + 4326376
1   chromedriver                        0x00000001047bc8b0 chromedriver + 4294832
2   chromedriver                        0x00000001043e8088 chromedriver + 278664
3   chromedriver                        0x00000001043e0e94 chromedriver + 249492
4   chromedriver                        0x00000001043d2658 chromedriver + 190040
5   chromedriver                        0x00000001043d391c chromedriver + 194844
6   chromedriver                        0x00000001043d2930 chromedriver + 190768
7   chromedriver                        0x00000001043d2378 chromedriver + 189304
8   chromedriver                        0x00000001043d2018 chromedriver + 188440
9   chromedriver                        0x00000001043cfe60 chromedriver + 179808
10  chromedriver                        0x00000001043d07fc chromedriver + 182268
11  chromedriver                        0x00000001043ea620 chromedriver + 288288
12  chromedriver                        0x0000000104463b14 chromedriver + 785172
13  chromedriver                        0x00000001044634f8 chromedriver + 783608
14  chromedriver                        0x000000010441f4e4 chromedriver + 505060
15  chromedriver                        0x000000010441ff5c chromedriver + 507740
16  chromedriver                        0x0000000104787984 chromedriver + 4077956
17  chromedriver                        0x000000010478c73c chromedriver + 4097852
18  chromedriver                        0x000000010476e528 chromedriver + 3974440
19  chromedriver                        0x000000010478d054 chromedriver + 4100180
20  chromedriver                        0x000000010475fb18 chromedriver + 3914520
21  chromedriver                        0x00000001047ad65c chromedriver + 4232796
22  chromedriver                        0x00000001047ad7d8 chromedriver + 4233176
23  chromedriver                        0x00000001047bc524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 09:54:30/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 206, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 79, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 89, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000100ed43e8 chromedriver + 4326376
1   chromedriver                        0x0000000100ecc8b0 chromedriver + 4294832
2   chromedriver                        0x0000000100af8088 chromedriver + 278664
3   chromedriver                        0x0000000100af0e94 chromedriver + 249492
4   chromedriver                        0x0000000100ae2658 chromedriver + 190040
5   chromedriver                        0x0000000100ae391c chromedriver + 194844
6   chromedriver                        0x0000000100ae2930 chromedriver + 190768
7   chromedriver                        0x0000000100ae2378 chromedriver + 189304
8   chromedriver                        0x0000000100ae2018 chromedriver + 188440
9   chromedriver                        0x0000000100adfe60 chromedriver + 179808
10  chromedriver                        0x0000000100ae07fc chromedriver + 182268
11  chromedriver                        0x0000000100afa620 chromedriver + 288288
12  chromedriver                        0x0000000100b73b14 chromedriver + 785172
13  chromedriver                        0x0000000100b734f8 chromedriver + 783608
14  chromedriver                        0x0000000100b2f4e4 chromedriver + 505060
15  chromedriver                        0x0000000100b2ff5c chromedriver + 507740
16  chromedriver                        0x0000000100e97984 chromedriver + 4077956
17  chromedriver                        0x0000000100e9c73c chromedriver + 4097852
18  chromedriver                        0x0000000100e7e528 chromedriver + 3974440
19  chromedriver                        0x0000000100e9d054 chromedriver + 4100180
20  chromedriver                        0x0000000100e6fb18 chromedriver + 3914520
21  chromedriver                        0x0000000100ebd65c chromedriver + 4232796
22  chromedriver                        0x0000000100ebd7d8 chromedriver + 4233176
23  chromedriver                        0x0000000100ecc524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 09:55:25/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 206, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 79, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 89, in dashboard
    driver.get("https://www.naver.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102eb03e8 chromedriver + 4326376
1   chromedriver                        0x0000000102ea88b0 chromedriver + 4294832
2   chromedriver                        0x0000000102ad4088 chromedriver + 278664
3   chromedriver                        0x0000000102acce94 chromedriver + 249492
4   chromedriver                        0x0000000102abe658 chromedriver + 190040
5   chromedriver                        0x0000000102abf91c chromedriver + 194844
6   chromedriver                        0x0000000102abe930 chromedriver + 190768
7   chromedriver                        0x0000000102abe378 chromedriver + 189304
8   chromedriver                        0x0000000102abe018 chromedriver + 188440
9   chromedriver                        0x0000000102abbe60 chromedriver + 179808
10  chromedriver                        0x0000000102abc7fc chromedriver + 182268
11  chromedriver                        0x0000000102ad6620 chromedriver + 288288
12  chromedriver                        0x0000000102b4fb14 chromedriver + 785172
13  chromedriver                        0x0000000102b4f4f8 chromedriver + 783608
14  chromedriver                        0x0000000102b0b4e4 chromedriver + 505060
15  chromedriver                        0x0000000102b0bf5c chromedriver + 507740
16  chromedriver                        0x0000000102e73984 chromedriver + 4077956
17  chromedriver                        0x0000000102e7873c chromedriver + 4097852
18  chromedriver                        0x0000000102e5a528 chromedriver + 3974440
19  chromedriver                        0x0000000102e79054 chromedriver + 4100180
20  chromedriver                        0x0000000102e4bb18 chromedriver + 3914520
21  chromedriver                        0x0000000102e9965c chromedriver + 4232796
22  chromedriver                        0x0000000102e997d8 chromedriver + 4233176
23  chromedriver                        0x0000000102ea8524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 10:52:44/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 204, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 77, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 87, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001047f43e8 chromedriver + 4326376
1   chromedriver                        0x00000001047ec8b0 chromedriver + 4294832
2   chromedriver                        0x0000000104418088 chromedriver + 278664
3   chromedriver                        0x0000000104410e94 chromedriver + 249492
4   chromedriver                        0x0000000104402658 chromedriver + 190040
5   chromedriver                        0x000000010440391c chromedriver + 194844
6   chromedriver                        0x0000000104402930 chromedriver + 190768
7   chromedriver                        0x0000000104402378 chromedriver + 189304
8   chromedriver                        0x0000000104402018 chromedriver + 188440
9   chromedriver                        0x00000001043ffe60 chromedriver + 179808
10  chromedriver                        0x00000001044007fc chromedriver + 182268
11  chromedriver                        0x000000010441a620 chromedriver + 288288
12  chromedriver                        0x0000000104493b14 chromedriver + 785172
13  chromedriver                        0x00000001044934f8 chromedriver + 783608
14  chromedriver                        0x000000010444f4e4 chromedriver + 505060
15  chromedriver                        0x000000010444ff5c chromedriver + 507740
16  chromedriver                        0x00000001047b7984 chromedriver + 4077956
17  chromedriver                        0x00000001047bc73c chromedriver + 4097852
18  chromedriver                        0x000000010479e528 chromedriver + 3974440
19  chromedriver                        0x00000001047bd054 chromedriver + 4100180
20  chromedriver                        0x000000010478fb18 chromedriver + 3914520
21  chromedriver                        0x00000001047dd65c chromedriver + 4232796
22  chromedriver                        0x00000001047dd7d8 chromedriver + 4233176
23  chromedriver                        0x00000001047ec524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 10:59:09/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 204, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 77, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 87, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001033d43e8 chromedriver + 4326376
1   chromedriver                        0x00000001033cc8b0 chromedriver + 4294832
2   chromedriver                        0x0000000102ff8088 chromedriver + 278664
3   chromedriver                        0x0000000102ff0e94 chromedriver + 249492
4   chromedriver                        0x0000000102fe2658 chromedriver + 190040
5   chromedriver                        0x0000000102fe391c chromedriver + 194844
6   chromedriver                        0x0000000102fe2930 chromedriver + 190768
7   chromedriver                        0x0000000102fe2378 chromedriver + 189304
8   chromedriver                        0x0000000102fe2018 chromedriver + 188440
9   chromedriver                        0x0000000102fdfe60 chromedriver + 179808
10  chromedriver                        0x0000000102fe07fc chromedriver + 182268
11  chromedriver                        0x0000000102ffa620 chromedriver + 288288
12  chromedriver                        0x0000000103073b14 chromedriver + 785172
13  chromedriver                        0x00000001030734f8 chromedriver + 783608
14  chromedriver                        0x000000010302f4e4 chromedriver + 505060
15  chromedriver                        0x000000010302ff5c chromedriver + 507740
16  chromedriver                        0x0000000103397984 chromedriver + 4077956
17  chromedriver                        0x000000010339c73c chromedriver + 4097852
18  chromedriver                        0x000000010337e528 chromedriver + 3974440
19  chromedriver                        0x000000010339d054 chromedriver + 4100180
20  chromedriver                        0x000000010336fb18 chromedriver + 3914520
21  chromedriver                        0x00000001033bd65c chromedriver + 4232796
22  chromedriver                        0x00000001033bd7d8 chromedriver + 4233176
23  chromedriver                        0x00000001033cc524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 10:59:57/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 204, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 77, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 87, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001045443e8 chromedriver + 4326376
1   chromedriver                        0x000000010453c8b0 chromedriver + 4294832
2   chromedriver                        0x0000000104168088 chromedriver + 278664
3   chromedriver                        0x0000000104160e94 chromedriver + 249492
4   chromedriver                        0x0000000104152658 chromedriver + 190040
5   chromedriver                        0x000000010415391c chromedriver + 194844
6   chromedriver                        0x0000000104152930 chromedriver + 190768
7   chromedriver                        0x0000000104152378 chromedriver + 189304
8   chromedriver                        0x0000000104152018 chromedriver + 188440
9   chromedriver                        0x000000010414fe60 chromedriver + 179808
10  chromedriver                        0x00000001041507fc chromedriver + 182268
11  chromedriver                        0x000000010416a620 chromedriver + 288288
12  chromedriver                        0x00000001041e3b14 chromedriver + 785172
13  chromedriver                        0x00000001041e34f8 chromedriver + 783608
14  chromedriver                        0x000000010419f4e4 chromedriver + 505060
15  chromedriver                        0x000000010419ff5c chromedriver + 507740
16  chromedriver                        0x0000000104507984 chromedriver + 4077956
17  chromedriver                        0x000000010450c73c chromedriver + 4097852
18  chromedriver                        0x00000001044ee528 chromedriver + 3974440
19  chromedriver                        0x000000010450d054 chromedriver + 4100180
20  chromedriver                        0x00000001044dfb18 chromedriver + 3914520
21  chromedriver                        0x000000010452d65c chromedriver + 4232796
22  chromedriver                        0x000000010452d7d8 chromedriver + 4233176
23  chromedriver                        0x000000010453c524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 11:00:04/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 204, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 77, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 87, in dashboard
    driver.get("https://www.instagram.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102f0c3e8 chromedriver + 4326376
1   chromedriver                        0x0000000102f048b0 chromedriver + 4294832
2   chromedriver                        0x0000000102b30088 chromedriver + 278664
3   chromedriver                        0x0000000102b28e94 chromedriver + 249492
4   chromedriver                        0x0000000102b1a658 chromedriver + 190040
5   chromedriver                        0x0000000102b1b91c chromedriver + 194844
6   chromedriver                        0x0000000102b1a930 chromedriver + 190768
7   chromedriver                        0x0000000102b1a378 chromedriver + 189304
8   chromedriver                        0x0000000102b1a018 chromedriver + 188440
9   chromedriver                        0x0000000102b17e60 chromedriver + 179808
10  chromedriver                        0x0000000102b187fc chromedriver + 182268
11  chromedriver                        0x0000000102b32620 chromedriver + 288288
12  chromedriver                        0x0000000102babb14 chromedriver + 785172
13  chromedriver                        0x0000000102bab4f8 chromedriver + 783608
14  chromedriver                        0x0000000102b674e4 chromedriver + 505060
15  chromedriver                        0x0000000102b67f5c chromedriver + 507740
16  chromedriver                        0x0000000102ecf984 chromedriver + 4077956
17  chromedriver                        0x0000000102ed473c chromedriver + 4097852
18  chromedriver                        0x0000000102eb6528 chromedriver + 3974440
19  chromedriver                        0x0000000102ed5054 chromedriver + 4100180
20  chromedriver                        0x0000000102ea7b18 chromedriver + 3914520
21  chromedriver                        0x0000000102ef565c chromedriver + 4232796
22  chromedriver                        0x0000000102ef57d8 chromedriver + 4233176
23  chromedriver                        0x0000000102f04524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 11:01:20/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 210, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 97, in dashboard
    current_ip = driver.find_element_by_css_selector('.ip').text
AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'

8867/2024-04-19 11:02:58/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 211, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 97, in dashboard
    current_ip = common.find_element("CSS_SELECTOR", ".ip", driver, wait)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 136, in find_element
    return wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector_name)))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x00000001011f83e8 chromedriver + 4326376
1   chromedriver                        0x00000001011f08b0 chromedriver + 4294832
2   chromedriver                        0x0000000100e1c088 chromedriver + 278664
3   chromedriver                        0x0000000100e5ea80 chromedriver + 551552
4   chromedriver                        0x0000000100e974f8 chromedriver + 783608
5   chromedriver                        0x0000000100e534e4 chromedriver + 505060
6   chromedriver                        0x0000000100e53f5c chromedriver + 507740
7   chromedriver                        0x00000001011bb984 chromedriver + 4077956
8   chromedriver                        0x00000001011c073c chromedriver + 4097852
9   chromedriver                        0x00000001011a2528 chromedriver + 3974440
10  chromedriver                        0x00000001011c1054 chromedriver + 4100180
11  chromedriver                        0x0000000101193b18 chromedriver + 3914520
12  chromedriver                        0x00000001011e165c chromedriver + 4232796
13  chromedriver                        0x00000001011e17d8 chromedriver + 4233176
14  chromedriver                        0x00000001011f0524 chromedriver + 4293924
15  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 11:08:34/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 207, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 93, in dashboard
    driver.get("https://www.google.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001049d43e8 chromedriver + 4326376
1   chromedriver                        0x00000001049cc8b0 chromedriver + 4294832
2   chromedriver                        0x00000001045f8088 chromedriver + 278664
3   chromedriver                        0x00000001045f0e94 chromedriver + 249492
4   chromedriver                        0x00000001045e2658 chromedriver + 190040
5   chromedriver                        0x00000001045e391c chromedriver + 194844
6   chromedriver                        0x00000001045e2930 chromedriver + 190768
7   chromedriver                        0x00000001045e2378 chromedriver + 189304
8   chromedriver                        0x00000001045e2018 chromedriver + 188440
9   chromedriver                        0x00000001045dfe60 chromedriver + 179808
10  chromedriver                        0x00000001045e07fc chromedriver + 182268
11  chromedriver                        0x00000001045fa620 chromedriver + 288288
12  chromedriver                        0x0000000104673b14 chromedriver + 785172
13  chromedriver                        0x00000001046734f8 chromedriver + 783608
14  chromedriver                        0x000000010462f4e4 chromedriver + 505060
15  chromedriver                        0x000000010462ff5c chromedriver + 507740
16  chromedriver                        0x0000000104997984 chromedriver + 4077956
17  chromedriver                        0x000000010499c73c chromedriver + 4097852
18  chromedriver                        0x000000010497e528 chromedriver + 3974440
19  chromedriver                        0x000000010499d054 chromedriver + 4100180
20  chromedriver                        0x000000010496fb18 chromedriver + 3914520
21  chromedriver                        0x00000001049bd65c chromedriver + 4232796
22  chromedriver                        0x00000001049bd7d8 chromedriver + 4233176
23  chromedriver                        0x00000001049cc524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 11:08:44/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 206, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 82, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 92, in dashboard
    driver.get("https://www.google.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102b843e8 chromedriver + 4326376
1   chromedriver                        0x0000000102b7c8b0 chromedriver + 4294832
2   chromedriver                        0x00000001027a8088 chromedriver + 278664
3   chromedriver                        0x00000001027a0e94 chromedriver + 249492
4   chromedriver                        0x0000000102792658 chromedriver + 190040
5   chromedriver                        0x000000010279391c chromedriver + 194844
6   chromedriver                        0x0000000102792930 chromedriver + 190768
7   chromedriver                        0x0000000102792378 chromedriver + 189304
8   chromedriver                        0x0000000102792018 chromedriver + 188440
9   chromedriver                        0x000000010278fe60 chromedriver + 179808
10  chromedriver                        0x00000001027907fc chromedriver + 182268
11  chromedriver                        0x00000001027aa620 chromedriver + 288288
12  chromedriver                        0x0000000102823b14 chromedriver + 785172
13  chromedriver                        0x00000001028234f8 chromedriver + 783608
14  chromedriver                        0x00000001027df4e4 chromedriver + 505060
15  chromedriver                        0x00000001027dff5c chromedriver + 507740
16  chromedriver                        0x0000000102b47984 chromedriver + 4077956
17  chromedriver                        0x0000000102b4c73c chromedriver + 4097852
18  chromedriver                        0x0000000102b2e528 chromedriver + 3974440
19  chromedriver                        0x0000000102b4d054 chromedriver + 4100180
20  chromedriver                        0x0000000102b1fb18 chromedriver + 3914520
21  chromedriver                        0x0000000102b6d65c chromedriver + 4232796
22  chromedriver                        0x0000000102b6d7d8 chromedriver + 4233176
23  chromedriver                        0x0000000102b7c524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 11:10:19/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 208, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 94, in dashboard
    driver.get("https://www.google.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x000000010085c3e8 chromedriver + 4326376
1   chromedriver                        0x00000001008548b0 chromedriver + 4294832
2   chromedriver                        0x0000000100480088 chromedriver + 278664
3   chromedriver                        0x0000000100478e94 chromedriver + 249492
4   chromedriver                        0x000000010046a658 chromedriver + 190040
5   chromedriver                        0x000000010046b91c chromedriver + 194844
6   chromedriver                        0x000000010046a930 chromedriver + 190768
7   chromedriver                        0x000000010046a378 chromedriver + 189304
8   chromedriver                        0x000000010046a018 chromedriver + 188440
9   chromedriver                        0x0000000100467e60 chromedriver + 179808
10  chromedriver                        0x00000001004687fc chromedriver + 182268
11  chromedriver                        0x0000000100482620 chromedriver + 288288
12  chromedriver                        0x00000001004fbb14 chromedriver + 785172
13  chromedriver                        0x00000001004fb4f8 chromedriver + 783608
14  chromedriver                        0x00000001004b74e4 chromedriver + 505060
15  chromedriver                        0x00000001004b7f5c chromedriver + 507740
16  chromedriver                        0x000000010081f984 chromedriver + 4077956
17  chromedriver                        0x000000010082473c chromedriver + 4097852
18  chromedriver                        0x0000000100806528 chromedriver + 3974440
19  chromedriver                        0x0000000100825054 chromedriver + 4100180
20  chromedriver                        0x00000001007f7b18 chromedriver + 3914520
21  chromedriver                        0x000000010084565c chromedriver + 4232796
22  chromedriver                        0x00000001008457d8 chromedriver + 4233176
23  chromedriver                        0x0000000100854524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 11:10:46/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 208, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 94, in dashboard
    driver.get("https://www.google.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001026303e8 chromedriver + 4326376
1   chromedriver                        0x00000001026288b0 chromedriver + 4294832
2   chromedriver                        0x0000000102254088 chromedriver + 278664
3   chromedriver                        0x000000010224ce94 chromedriver + 249492
4   chromedriver                        0x000000010223e658 chromedriver + 190040
5   chromedriver                        0x000000010223f91c chromedriver + 194844
6   chromedriver                        0x000000010223e930 chromedriver + 190768
7   chromedriver                        0x000000010223e378 chromedriver + 189304
8   chromedriver                        0x000000010223e018 chromedriver + 188440
9   chromedriver                        0x000000010223be60 chromedriver + 179808
10  chromedriver                        0x000000010223c7fc chromedriver + 182268
11  chromedriver                        0x0000000102256620 chromedriver + 288288
12  chromedriver                        0x00000001022cfb14 chromedriver + 785172
13  chromedriver                        0x00000001022cf4f8 chromedriver + 783608
14  chromedriver                        0x000000010228b4e4 chromedriver + 505060
15  chromedriver                        0x000000010228bf5c chromedriver + 507740
16  chromedriver                        0x00000001025f3984 chromedriver + 4077956
17  chromedriver                        0x00000001025f873c chromedriver + 4097852
18  chromedriver                        0x00000001025da528 chromedriver + 3974440
19  chromedriver                        0x00000001025f9054 chromedriver + 4100180
20  chromedriver                        0x00000001025cbb18 chromedriver + 3914520
21  chromedriver                        0x000000010261965c chromedriver + 4232796
22  chromedriver                        0x00000001026197d8 chromedriver + 4233176
23  chromedriver                        0x0000000102628524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 11:11:46/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 208, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 84, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 94, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102d783e8 chromedriver + 4326376
1   chromedriver                        0x0000000102d708b0 chromedriver + 4294832
2   chromedriver                        0x000000010299c088 chromedriver + 278664
3   chromedriver                        0x0000000102994e94 chromedriver + 249492
4   chromedriver                        0x0000000102986658 chromedriver + 190040
5   chromedriver                        0x000000010298791c chromedriver + 194844
6   chromedriver                        0x0000000102986930 chromedriver + 190768
7   chromedriver                        0x0000000102986378 chromedriver + 189304
8   chromedriver                        0x0000000102986018 chromedriver + 188440
9   chromedriver                        0x0000000102983e60 chromedriver + 179808
10  chromedriver                        0x00000001029847fc chromedriver + 182268
11  chromedriver                        0x000000010299e620 chromedriver + 288288
12  chromedriver                        0x0000000102a17b14 chromedriver + 785172
13  chromedriver                        0x0000000102a174f8 chromedriver + 783608
14  chromedriver                        0x00000001029d34e4 chromedriver + 505060
15  chromedriver                        0x00000001029d3f5c chromedriver + 507740
16  chromedriver                        0x0000000102d3b984 chromedriver + 4077956
17  chromedriver                        0x0000000102d4073c chromedriver + 4097852
18  chromedriver                        0x0000000102d22528 chromedriver + 3974440
19  chromedriver                        0x0000000102d41054 chromedriver + 4100180
20  chromedriver                        0x0000000102d13b18 chromedriver + 3914520
21  chromedriver                        0x0000000102d6165c chromedriver + 4232796
22  chromedriver                        0x0000000102d617d8 chromedriver + 4233176
23  chromedriver                        0x0000000102d70524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 12:07:50/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 210, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 86, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 104, in dashboard
    is_login = common.is_display("TAG_NAME", "loginForm", driver)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../common/fun.py", line 204, in is_display
    count = len(driver.find_elements(By.TAG_NAME, selector_name))
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 771, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102e583e8 chromedriver + 4326376
1   chromedriver                        0x0000000102e508b0 chromedriver + 4294832
2   chromedriver                        0x0000000102a7c088 chromedriver + 278664
3   chromedriver                        0x0000000102a57270 chromedriver + 127600
4   chromedriver                        0x0000000102ae39ac chromedriver + 702892
5   chromedriver                        0x0000000102af6c0c chromedriver + 781324
6   chromedriver                        0x0000000102ab34e4 chromedriver + 505060
7   chromedriver                        0x0000000102ab3f5c chromedriver + 507740
8   chromedriver                        0x0000000102e1b984 chromedriver + 4077956
9   chromedriver                        0x0000000102e2073c chromedriver + 4097852
10  chromedriver                        0x0000000102e02528 chromedriver + 3974440
11  chromedriver                        0x0000000102e21054 chromedriver + 4100180
12  chromedriver                        0x0000000102df3b18 chromedriver + 3914520
13  chromedriver                        0x0000000102e4165c chromedriver + 4232796
14  chromedriver                        0x0000000102e417d8 chromedriver + 4233176
15  chromedriver                        0x0000000102e50524 chromedriver + 4293924
16  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 12:19:41/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 220, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 65, in setup
    print(f"- 작동 여부: {result['working']}")
TypeError: 'bool' object is not subscriptable

8867/2024-04-19 12:21:05/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 220, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 65, in setup
    print(f"- 작동 여부: {result['working']}")
TypeError: 'bool' object is not subscriptable

8867/2024-04-19 12:22:04/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 220, in mainFun
    try:
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 65, in setup
    print(f"프록시3 {result}")
TypeError: 'bool' object is not subscriptable

8867/2024-04-19 12:22:48/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 221, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 66, in setup
    print(f"- 작동 여부: {result['working']}")
TypeError: 'bool' object is not subscriptable

8867/2024-04-19 12:56:54/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 208, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 78, in setup
    selenium_driver = webdriver.Chrome(service=service, options=options)
NameError: name 'service' is not defined

8867/2024-04-19 12:58:41/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 208, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 78, in setup
    selenium_driver = webdriver.Chrome(chromedriver_path, options=options)
TypeError: WebDriver.__init__() got multiple values for argument 'options'

8867/2024-04-19 13:01:39/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 194, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 80, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001025383e8 chromedriver + 4326376
1   chromedriver                        0x00000001025308b0 chromedriver + 4294832
2   chromedriver                        0x000000010215c088 chromedriver + 278664
3   chromedriver                        0x0000000102154e94 chromedriver + 249492
4   chromedriver                        0x0000000102146658 chromedriver + 190040
5   chromedriver                        0x000000010214791c chromedriver + 194844
6   chromedriver                        0x0000000102146930 chromedriver + 190768
7   chromedriver                        0x0000000102146378 chromedriver + 189304
8   chromedriver                        0x0000000102146018 chromedriver + 188440
9   chromedriver                        0x0000000102143e60 chromedriver + 179808
10  chromedriver                        0x00000001021447fc chromedriver + 182268
11  chromedriver                        0x000000010215e620 chromedriver + 288288
12  chromedriver                        0x00000001021d7b14 chromedriver + 785172
13  chromedriver                        0x00000001021d74f8 chromedriver + 783608
14  chromedriver                        0x00000001021934e4 chromedriver + 505060
15  chromedriver                        0x0000000102193f5c chromedriver + 507740
16  chromedriver                        0x00000001024fb984 chromedriver + 4077956
17  chromedriver                        0x000000010250073c chromedriver + 4097852
18  chromedriver                        0x00000001024e2528 chromedriver + 3974440
19  chromedriver                        0x0000000102501054 chromedriver + 4100180
20  chromedriver                        0x00000001024d3b18 chromedriver + 3914520
21  chromedriver                        0x000000010252165c chromedriver + 4232796
22  chromedriver                        0x00000001025217d8 chromedriver + 4233176
23  chromedriver                        0x0000000102530524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:02:32/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 197, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 73, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000100b244a4 chromedriver + 4326564
1   chromedriver                        0x0000000100b1c96c chromedriver + 4295020
2   chromedriver                        0x0000000100748088 chromedriver + 278664
3   chromedriver                        0x0000000100740e94 chromedriver + 249492
4   chromedriver                        0x0000000100732658 chromedriver + 190040
5   chromedriver                        0x000000010073391c chromedriver + 194844
6   chromedriver                        0x0000000100732930 chromedriver + 190768
7   chromedriver                        0x0000000100732378 chromedriver + 189304
8   chromedriver                        0x0000000100732018 chromedriver + 188440
9   chromedriver                        0x000000010072fe60 chromedriver + 179808
10  chromedriver                        0x00000001007307fc chromedriver + 182268
11  chromedriver                        0x000000010074a620 chromedriver + 288288
12  chromedriver                        0x00000001007c3b14 chromedriver + 785172
13  chromedriver                        0x00000001007c34f8 chromedriver + 783608
14  chromedriver                        0x000000010077f4e4 chromedriver + 505060
15  chromedriver                        0x000000010077ff5c chromedriver + 507740
16  chromedriver                        0x0000000100ae7a40 chromedriver + 4078144
17  chromedriver                        0x0000000100aec7f8 chromedriver + 4098040
18  chromedriver                        0x0000000100ace5e4 chromedriver + 3974628
19  chromedriver                        0x0000000100aed110 chromedriver + 4100368
20  chromedriver                        0x0000000100abfbd4 chromedriver + 3914708
21  chromedriver                        0x0000000100b0d718 chromedriver + 4232984
22  chromedriver                        0x0000000100b0d894 chromedriver + 4233364
23  chromedriver                        0x0000000100b1c5e0 chromedriver + 4294112
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:06:11/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 197, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 73, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001013f84a4 chromedriver + 4326564
1   chromedriver                        0x00000001013f096c chromedriver + 4295020
2   chromedriver                        0x000000010101c088 chromedriver + 278664
3   chromedriver                        0x0000000101014e94 chromedriver + 249492
4   chromedriver                        0x0000000101006658 chromedriver + 190040
5   chromedriver                        0x000000010100791c chromedriver + 194844
6   chromedriver                        0x0000000101006930 chromedriver + 190768
7   chromedriver                        0x0000000101006378 chromedriver + 189304
8   chromedriver                        0x0000000101006018 chromedriver + 188440
9   chromedriver                        0x0000000101003e60 chromedriver + 179808
10  chromedriver                        0x00000001010047fc chromedriver + 182268
11  chromedriver                        0x000000010101e620 chromedriver + 288288
12  chromedriver                        0x0000000101097b14 chromedriver + 785172
13  chromedriver                        0x00000001010974f8 chromedriver + 783608
14  chromedriver                        0x00000001010534e4 chromedriver + 505060
15  chromedriver                        0x0000000101053f5c chromedriver + 507740
16  chromedriver                        0x00000001013bba40 chromedriver + 4078144
17  chromedriver                        0x00000001013c07f8 chromedriver + 4098040
18  chromedriver                        0x00000001013a25e4 chromedriver + 3974628
19  chromedriver                        0x00000001013c1110 chromedriver + 4100368
20  chromedriver                        0x0000000101393bd4 chromedriver + 3914708
21  chromedriver                        0x00000001013e1718 chromedriver + 4232984
22  chromedriver                        0x00000001013e1894 chromedriver + 4233364
23  chromedriver                        0x00000001013f05e0 chromedriver + 4294112
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:07:51/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 227, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 97, in setup
    browser = webdriver.Firefox(firefox_profile=profile)  # 파이어폭스 열기
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'

8867/2024-04-19 13:08:10/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 227, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 97, in setup
    browser = webdriver.Firefox(firefox_profile=profile)  # 파이어폭스 열기
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'

8867/2024-04-19 13:09:20/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 197, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 73, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x00000001012484a4 chromedriver + 4326564
1   chromedriver                        0x000000010124096c chromedriver + 4295020
2   chromedriver                        0x0000000100e6c088 chromedriver + 278664
3   chromedriver                        0x0000000100e64e94 chromedriver + 249492
4   chromedriver                        0x0000000100e56658 chromedriver + 190040
5   chromedriver                        0x0000000100e5791c chromedriver + 194844
6   chromedriver                        0x0000000100e56930 chromedriver + 190768
7   chromedriver                        0x0000000100e56378 chromedriver + 189304
8   chromedriver                        0x0000000100e56018 chromedriver + 188440
9   chromedriver                        0x0000000100e53e60 chromedriver + 179808
10  chromedriver                        0x0000000100e547fc chromedriver + 182268
11  chromedriver                        0x0000000100e6e620 chromedriver + 288288
12  chromedriver                        0x0000000100ee7b14 chromedriver + 785172
13  chromedriver                        0x0000000100ee74f8 chromedriver + 783608
14  chromedriver                        0x0000000100ea34e4 chromedriver + 505060
15  chromedriver                        0x0000000100ea3f5c chromedriver + 507740
16  chromedriver                        0x000000010120ba40 chromedriver + 4078144
17  chromedriver                        0x00000001012107f8 chromedriver + 4098040
18  chromedriver                        0x00000001011f25e4 chromedriver + 3974628
19  chromedriver                        0x0000000101211110 chromedriver + 4100368
20  chromedriver                        0x00000001011e3bd4 chromedriver + 3914708
21  chromedriver                        0x0000000101231718 chromedriver + 4232984
22  chromedriver                        0x0000000101231894 chromedriver + 4233364
23  chromedriver                        0x00000001012405e0 chromedriver + 4294112
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:09:41/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 197, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 73, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000104c144a4 chromedriver + 4326564
1   chromedriver                        0x0000000104c0c96c chromedriver + 4295020
2   chromedriver                        0x0000000104838088 chromedriver + 278664
3   chromedriver                        0x0000000104830e94 chromedriver + 249492
4   chromedriver                        0x0000000104822658 chromedriver + 190040
5   chromedriver                        0x000000010482391c chromedriver + 194844
6   chromedriver                        0x0000000104822930 chromedriver + 190768
7   chromedriver                        0x0000000104822378 chromedriver + 189304
8   chromedriver                        0x0000000104822018 chromedriver + 188440
9   chromedriver                        0x000000010481fe60 chromedriver + 179808
10  chromedriver                        0x00000001048207fc chromedriver + 182268
11  chromedriver                        0x000000010483a620 chromedriver + 288288
12  chromedriver                        0x00000001048b3b14 chromedriver + 785172
13  chromedriver                        0x00000001048b34f8 chromedriver + 783608
14  chromedriver                        0x000000010486f4e4 chromedriver + 505060
15  chromedriver                        0x000000010486ff5c chromedriver + 507740
16  chromedriver                        0x0000000104bd7a40 chromedriver + 4078144
17  chromedriver                        0x0000000104bdc7f8 chromedriver + 4098040
18  chromedriver                        0x0000000104bbe5e4 chromedriver + 3974628
19  chromedriver                        0x0000000104bdd110 chromedriver + 4100368
20  chromedriver                        0x0000000104bafbd4 chromedriver + 3914708
21  chromedriver                        0x0000000104bfd718 chromedriver + 4232984
22  chromedriver                        0x0000000104bfd894 chromedriver + 4233364
23  chromedriver                        0x0000000104c0c5e0 chromedriver + 4294112
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:09:56/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 197, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 73, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102ba43e8 chromedriver + 4326376
1   chromedriver                        0x0000000102b9c8b0 chromedriver + 4294832
2   chromedriver                        0x00000001027c8088 chromedriver + 278664
3   chromedriver                        0x00000001027c0e94 chromedriver + 249492
4   chromedriver                        0x00000001027b2658 chromedriver + 190040
5   chromedriver                        0x00000001027b391c chromedriver + 194844
6   chromedriver                        0x00000001027b2930 chromedriver + 190768
7   chromedriver                        0x00000001027b2378 chromedriver + 189304
8   chromedriver                        0x00000001027b2018 chromedriver + 188440
9   chromedriver                        0x00000001027afe60 chromedriver + 179808
10  chromedriver                        0x00000001027b07fc chromedriver + 182268
11  chromedriver                        0x00000001027ca620 chromedriver + 288288
12  chromedriver                        0x0000000102843b14 chromedriver + 785172
13  chromedriver                        0x00000001028434f8 chromedriver + 783608
14  chromedriver                        0x00000001027ff4e4 chromedriver + 505060
15  chromedriver                        0x00000001027fff5c chromedriver + 507740
16  chromedriver                        0x0000000102b67984 chromedriver + 4077956
17  chromedriver                        0x0000000102b6c73c chromedriver + 4097852
18  chromedriver                        0x0000000102b4e528 chromedriver + 3974440
19  chromedriver                        0x0000000102b6d054 chromedriver + 4100180
20  chromedriver                        0x0000000102b3fb18 chromedriver + 3914520
21  chromedriver                        0x0000000102b8d65c chromedriver + 4232796
22  chromedriver                        0x0000000102b8d7d8 chromedriver + 4233176
23  chromedriver                        0x0000000102b9c524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:10:28/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 197, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 73, in setup
    return dashboard()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 83, in dashboard
    driver.get("https://dnsleaktest.com/")
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.124)
Stacktrace:
0   chromedriver                        0x0000000102b343e8 chromedriver + 4326376
1   chromedriver                        0x0000000102b2c8b0 chromedriver + 4294832
2   chromedriver                        0x0000000102758088 chromedriver + 278664
3   chromedriver                        0x0000000102750e94 chromedriver + 249492
4   chromedriver                        0x0000000102742658 chromedriver + 190040
5   chromedriver                        0x000000010274391c chromedriver + 194844
6   chromedriver                        0x0000000102742930 chromedriver + 190768
7   chromedriver                        0x0000000102742378 chromedriver + 189304
8   chromedriver                        0x0000000102742018 chromedriver + 188440
9   chromedriver                        0x000000010273fe60 chromedriver + 179808
10  chromedriver                        0x00000001027407fc chromedriver + 182268
11  chromedriver                        0x000000010275a620 chromedriver + 288288
12  chromedriver                        0x00000001027d3b14 chromedriver + 785172
13  chromedriver                        0x00000001027d34f8 chromedriver + 783608
14  chromedriver                        0x000000010278f4e4 chromedriver + 505060
15  chromedriver                        0x000000010278ff5c chromedriver + 507740
16  chromedriver                        0x0000000102af7984 chromedriver + 4077956
17  chromedriver                        0x0000000102afc73c chromedriver + 4097852
18  chromedriver                        0x0000000102ade528 chromedriver + 3974440
19  chromedriver                        0x0000000102afd054 chromedriver + 4100180
20  chromedriver                        0x0000000102acfb18 chromedriver + 3914520
21  chromedriver                        0x0000000102b1d65c chromedriver + 4232796
22  chromedriver                        0x0000000102b1d7d8 chromedriver + 4233176
23  chromedriver                        0x0000000102b2c524 chromedriver + 4293924
24  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
25  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:13:13/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 206, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    selenium_driver = webdriver.Chrome()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: proxy
from invalid argument: unrecognized proxy type: MANUAL
Stacktrace:
0   chromedriver                        0x0000000102a884a4 chromedriver + 4326564
1   chromedriver                        0x0000000102a8096c chromedriver + 4295020
2   chromedriver                        0x00000001026ac088 chromedriver + 278664
3   chromedriver                        0x00000001026ce72c chromedriver + 419628
4   chromedriver                        0x00000001026cd764 chromedriver + 415588
5   chromedriver                        0x0000000102715908 chromedriver + 710920
6   chromedriver                        0x0000000102715300 chromedriver + 709376
7   chromedriver                        0x0000000102716b44 chromedriver + 715588
8   chromedriver                        0x00000001026e34e4 chromedriver + 505060
9   chromedriver                        0x00000001026e3f5c chromedriver + 507740
10  chromedriver                        0x0000000102a4ba40 chromedriver + 4078144
11  chromedriver                        0x0000000102a507f8 chromedriver + 4098040
12  chromedriver                        0x0000000102a325e4 chromedriver + 3974628
13  chromedriver                        0x0000000102a51110 chromedriver + 4100368
14  chromedriver                        0x0000000102a23bd4 chromedriver + 3914708
15  chromedriver                        0x0000000102a71718 chromedriver + 4232984
16  chromedriver                        0x0000000102a71894 chromedriver + 4233364
17  chromedriver                        0x0000000102a805e0 chromedriver + 4294112
18  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
19  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 13:13:37/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 206, in mainFun
    return setup()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 70, in setup
    selenium_driver = webdriver.Chrome()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: proxy
from invalid argument: unrecognized proxy type: MANUAL
Stacktrace:
0   chromedriver                        0x000000010106c4a4 chromedriver + 4326564
1   chromedriver                        0x000000010106496c chromedriver + 4295020
2   chromedriver                        0x0000000100c90088 chromedriver + 278664
3   chromedriver                        0x0000000100cb272c chromedriver + 419628
4   chromedriver                        0x0000000100cb1764 chromedriver + 415588
5   chromedriver                        0x0000000100cf9908 chromedriver + 710920
6   chromedriver                        0x0000000100cf9300 chromedriver + 709376
7   chromedriver                        0x0000000100cfab44 chromedriver + 715588
8   chromedriver                        0x0000000100cc74e4 chromedriver + 505060
9   chromedriver                        0x0000000100cc7f5c chromedriver + 507740
10  chromedriver                        0x000000010102fa40 chromedriver + 4078144
11  chromedriver                        0x00000001010347f8 chromedriver + 4098040
12  chromedriver                        0x00000001010165e4 chromedriver + 3974628
13  chromedriver                        0x0000000101035110 chromedriver + 4100368
14  chromedriver                        0x0000000101007bd4 chromedriver + 3914708
15  chromedriver                        0x0000000101055718 chromedriver + 4232984
16  chromedriver                        0x0000000101055894 chromedriver + 4233364
17  chromedriver                        0x00000001010645e0 chromedriver + 4294112
18  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
19  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


8867/2024-04-19 15:04:13/Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 142, in save
    save_element.click()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div>...</div> is not clickable at point (457, 741). Other element would receive the click: <div class="xjp7ctv xir0mxb x19osjzx">...</div>
  (Session info: chrome=124.0.6367.61)
Stacktrace:
0   chromedriver                        0x00000001011903e8 chromedriver + 4326376
1   chromedriver                        0x00000001011888b0 chromedriver + 4294832
2   chromedriver                        0x0000000100db4088 chromedriver + 278664
3   chromedriver                        0x0000000100dfc554 chromedriver + 574804
4   chromedriver                        0x0000000100dfaad8 chromedriver + 568024
5   chromedriver                        0x0000000100df8c58 chromedriver + 560216
6   chromedriver                        0x0000000100df8188 chromedriver + 557448
7   chromedriver                        0x0000000100ded3ac chromedriver + 512940
8   chromedriver                        0x0000000100decdd0 chromedriver + 511440
9   chromedriver                        0x0000000100e2f4f8 chromedriver + 783608
10  chromedriver                        0x0000000100deb4e4 chromedriver + 505060
11  chromedriver                        0x0000000100debf5c chromedriver + 507740
12  chromedriver                        0x0000000101153984 chromedriver + 4077956
13  chromedriver                        0x000000010115873c chromedriver + 4097852
14  chromedriver                        0x000000010113a528 chromedriver + 3974440
15  chromedriver                        0x0000000101159054 chromedriver + 4100180
16  chromedriver                        0x000000010112bb18 chromedriver + 3914520
17  chromedriver                        0x000000010117965c chromedriver + 4232796
18  chromedriver                        0x00000001011797d8 chromedriver + 4233176
19  chromedriver                        0x0000000101188524 chromedriver + 4293924
20  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
21  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 129, in fetch_order
    result, message = save()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 148, in save
    raise Exception(ex)
Exception: Message: element click intercepted: Element <div>...</div> is not clickable at point (457, 741). Other element would receive the click: <div class="xjp7ctv xir0mxb x19osjzx">...</div>
  (Session info: chrome=124.0.6367.61)
Stacktrace:
0   chromedriver                        0x00000001011903e8 chromedriver + 4326376
1   chromedriver                        0x00000001011888b0 chromedriver + 4294832
2   chromedriver                        0x0000000100db4088 chromedriver + 278664
3   chromedriver                        0x0000000100dfc554 chromedriver + 574804
4   chromedriver                        0x0000000100dfaad8 chromedriver + 568024
5   chromedriver                        0x0000000100df8c58 chromedriver + 560216
6   chromedriver                        0x0000000100df8188 chromedriver + 557448
7   chromedriver                        0x0000000100ded3ac chromedriver + 512940
8   chromedriver                        0x0000000100decdd0 chromedriver + 511440
9   chromedriver                        0x0000000100e2f4f8 chromedriver + 783608
10  chromedriver                        0x0000000100deb4e4 chromedriver + 505060
11  chromedriver                        0x0000000100debf5c chromedriver + 507740
12  chromedriver                        0x0000000101153984 chromedriver + 4077956
13  chromedriver                        0x000000010115873c chromedriver + 4097852
14  chromedriver                        0x000000010113a528 chromedriver + 3974440
15  chromedriver                        0x0000000101159054 chromedriver + 4100180
16  chromedriver                        0x000000010112bb18 chromedriver + 3914520
17  chromedriver                        0x000000010117965c chromedriver + 4232796
18  chromedriver                        0x00000001011797d8 chromedriver + 4233176
19  chromedriver                        0x0000000101188524 chromedriver + 4293924
20  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
21  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 108, in dashboard
    result, message = fetch_order()
  File "/Volumes/Expansion/ohs/project/study/python/instahelp_web/save/../save/save_main.py", line 132, in fetch_order
    raise Exception(ex)
Exception: Message: element click intercepted: Element <div>...</div> is not clickable at point (457, 741). Other element would receive the click: <div class="xjp7ctv xir0mxb x19osjzx">...</div>
  (Session info: chrome=124.0.6367.61)
Stacktrace:
0   chromedriver                        0x00000001011903e8 chromedriver + 4326376
1   chromedriver                        0x00000001011888b0 chromedriver + 4294832
2   chromedriver                        0x0000000100db4088 chromedriver + 278664
3   chromedriver                        0x0000000100dfc554 chromedriver + 574804
4   chromedriver                        0x0000000100dfaad8 chromedriver + 568024
5   chromedriver                        0x0000000100df8c58 chromedriver + 560216
6   chromedriver                        0x0000000100df8188 chromedriver + 557448
7   chromedriver                        0x0000000100ded3ac chromedriver + 512940
8   chromedriver                        0x0000000100decdd0 chromedriver + 511440
9   chromedriver                        0x0000000100e2f4f8 chromedriver + 783608
10  chromedriver                        0x0000000100deb4e4 chromedriver + 505060
11  chromedriver                        0x0000000100debf5c chromedriver + 507740
12  chromedriver                        0x0000000101153984 chromedriver + 4077956
13  chromedriver                        0x000000010115873c chromedriver + 4097852
14  chromedriver                        0x000000010113a528 chromedriver + 3974440
15  chromedriver                        0x0000000101159054 chromedriver + 4100180
16  chromedriver                        0x000000010112bb18 chromedriver + 3914520
17  chromedriver                        0x000000010117965c chromedriver + 4232796
18  chromedriver                        0x00000001011797d8 chromedriver + 4233176
19  chromedriver                        0x0000000101188524 chromedriver + 4293924
20  libsystem_pthread.dylib             0x0000000184cd6f94 _pthread_start + 136
21  libsystem_pthread.dylib             0x0000000184cd1d34 thread_start + 8


