[1][cinequkuyybe91] 초기 메모리 사용량: 51.46 MB
[1][cinequkuyybe91] 셀레니움 연결
[1][cinequkuyybe91] 셀레니움 연결
[1][cinequkuyybe91] Traceback (most recent call last):
  File "/instahelp_web/docker_follow/follow_main.py", line 48, in setup
    driver = common.open_selenium(current_os, wait_time, ip, session_id, tab_index)
  File "/instahelp_web/common/fun.py", line 781, in open_selenium
    selenium_driver = webdriver.Chrome(service=service, options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5631eed2e6aa <unknown>
#1 0x5631eea110dc <unknown>
#2 0x5631eea4602a <unknown>
#3 0x5631eea4243b <unknown>
#4 0x5631eea8cef9 <unknown>
#5 0x5631eea80613 <unknown>
#6 0x5631eea504f7 <unknown>
#7 0x5631eea50e4e <unknown>
#8 0x5631eecf487b <unknown>
#9 0x5631eecf8921 <unknown>
#10 0x5631eece036e <unknown>
#11 0x5631eecf9482 <unknown>
#12 0x5631eecc4ccf <unknown>
#13 0x5631eed1e0a8 <unknown>
#14 0x5631eed1e280 <unknown>
#15 0x5631eed2d7dc <unknown>
#16 0x7f0c5e20a134 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/instahelp_web/docker_follow/follow_main.py", line 290, in main_fun
    result = setup()
  File "/instahelp_web/docker_follow/follow_main.py", line 51, in setup
    driver = common.open_selenium(current_os, wait_time, ip, session_id, tab_index)
  File "/instahelp_web/common/fun.py", line 781, in open_selenium
    selenium_driver = webdriver.Chrome(service=service, options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x562c516326aa <unknown>
#1 0x562c513150dc <unknown>
#2 0x562c5134a02a <unknown>
#3 0x562c5134643b <unknown>
#4 0x562c51390ef9 <unknown>
#5 0x562c51384613 <unknown>
#6 0x562c513544f7 <unknown>
#7 0x562c51354e4e <unknown>
#8 0x562c515f887b <unknown>
#9 0x562c515fc921 <unknown>
#10 0x562c515e436e <unknown>
#11 0x562c515fd482 <unknown>
#12 0x562c515c8ccf <unknown>
#13 0x562c516220a8 <unknown>
#14 0x562c51622280 <unknown>
#15 0x562c516317dc <unknown>
#16 0x7f01ea7a1134 <unknown>


[1][cinequkuyybe91] Task[0,1,에러발생]
[1][cinequkuyybe91] 마지막 메모리 사용량: 52.98 MB
