[10][vominhthong8749] 로그인 시작
[10][vominhthong8749] 로그인 종료
[10][vominhthong8749] 로그인 검증 시작
[10][vominhthong8749] 동의여부 체크 시작
[10][vominhthong8749] 동의여부 체크 종료 : 동의 필요하지 않음
[10][vominhthong8749] 로그인 검증 종료
[10][vominhthong8749] 로그인 성공여부 True - True
[10][vominhthong8749] 남은 수량 : 1
[10][vominhthong8749] 동의여부 체크 시작
[10][vominhthong8749] Traceback (most recent call last):
  File "/instahelp_web/docker_follow/follow_main.py", line 221, in fetch_order
    if common.agree_check(user_id, tab_index, driver, wait):
  File "/instahelp_web/common/fun.py", line 803, in agree_check
    if agree.text == 'Instagram 앱을 사용하려면 다음 항목에 동의해야 합니다':
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome-headless-shell=126.0.6478.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5598aa0766aa <unknown>
#1 0x5598a9d590dc <unknown>
#2 0x5598a9d5e7e9 <unknown>
#3 0x5598a9d60595 <unknown>
#4 0x5598a9d6061c <unknown>
#5 0x5598a9d9fae2 <unknown>
#6 0x5598a9dc8872 <unknown>
#7 0x5598a9d99d89 <unknown>
#8 0x5598a9dc8a3e <unknown>
#9 0x5598a9de75c3 <unknown>
#10 0x5598a9dc8613 <unknown>
#11 0x5598a9d984f7 <unknown>
#12 0x5598a9d98e4e <unknown>
#13 0x5598aa03c87b <unknown>
#14 0x5598aa040921 <unknown>
#15 0x5598aa02836e <unknown>
#16 0x5598aa041482 <unknown>
#17 0x5598aa00cccf <unknown>
#18 0x5598aa0660a8 <unknown>
#19 0x5598aa066280 <unknown>
#20 0x5598aa0757dc <unknown>
#21 0x7fabb9ea4134 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/instahelp_web/docker_follow/follow_main.py", line 197, in dashboard
    result, message = fetch_order()
  File "/instahelp_web/docker_follow/follow_main.py", line 233, in fetch_order
    raise Exception(ex)
Exception: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome-headless-shell=126.0.6478.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5598aa0766aa <unknown>
#1 0x5598a9d590dc <unknown>
#2 0x5598a9d5e7e9 <unknown>
#3 0x5598a9d60595 <unknown>
#4 0x5598a9d6061c <unknown>
#5 0x5598a9d9fae2 <unknown>
#6 0x5598a9dc8872 <unknown>
#7 0x5598a9d99d89 <unknown>
#8 0x5598a9dc8a3e <unknown>
#9 0x5598a9de75c3 <unknown>
#10 0x5598a9dc8613 <unknown>
#11 0x5598a9d984f7 <unknown>
#12 0x5598a9d98e4e <unknown>
#13 0x5598aa03c87b <unknown>
#14 0x5598aa040921 <unknown>
#15 0x5598aa02836e <unknown>
#16 0x5598aa041482 <unknown>
#17 0x5598aa00cccf <unknown>
#18 0x5598aa0660a8 <unknown>
#19 0x5598aa066280 <unknown>
#20 0x5598aa0757dc <unknown>
#21 0x7fabb9ea4134 <unknown>


[10][vominhthong8749] Task[0,1,태스크 실패]
[10][vominhthong8749] 마지막 메모리 사용량: 13.21 MB
